version: "3"

services:
  # my-project-with-air:
  #   # working_dir value has to be the same of mapped volume
  #   working_dir: /project-package
  #   ports:
  #     - <any>:<any>
  #   environment:
  #     - ENV_A=${ENV_A}
  #     - ENV_B=${ENV_B}
  #     - ENV_C=${ENV_C}
  #   volumes:
  #     - ./project-relative-path/:/project-package/
  api:
    image: cosmtrek/air
    # build: .
    user: root
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      HOSTNAME: db
      JWT_SECRET: secretJWT
  redis:
    image: redis:7.0.2-alpine
    restart: always
  db:
    container_name: mongo_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
volumes:
  database: