version: "3"

services:
  my-app:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /project
    ports:
      - 8000:8000
    volumes:
      - ./:/project/ 
    links: 
    - mongodb
    container_name: my-app
    environment: 
    - PORT=8000
    - MONGO_HOST=mongodb
    - MONGO_USER=root
    - MONGO_PASSWORD=rootpassword
    - MONGO_PORT=27017
    - MONGO_DATABASE=starwars
  redis:
    image: redis:7.0.2-alpine
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
volumes:
  database: