version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:7.0.2-alpine
    restart: always
    networks:
      - dev
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - $MONGO_PORT:$MONGO_PORT
    networks:
      - dev
    depends_on:
      - mongo-seed
  mongo-seed:
    env_file:
      - .env
    build:
      context: ./mongo-seed
      dockerfile: Dockerfile
      args:
        - MONGO_PORT
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
    container_name: mongo-seed
    networks:
      - dev
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $PORT:$PORT
    depends_on:
      - mongo-seed
      - mongo
      - redis
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: always
    networks:
      - dev
networks:
  dev:
    driver: bridge