version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    environment: 
    - PORT=3001
    - MONGO_HOST=mongodb
    - MONGO_USER=root
    - MONGO_PASSWORD=rootpassword
    - MONGO_PORT=27017
    - MONGO_DATABASE=starwars
  redis:
    image: redis:7.0.2-alpine
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mogo_data:/data/db
volumes:
  mogo_data: