version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - redis
    volumes:
      - ./:/app
    environment: 
    - PORT=3001
  redis:
    image: redis:7.0.2-alpine
    restart: always